# Generated by Django 3.1 on 2022-05-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolling', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Rolling',
        ),
    ]
